export const employees = [
  {
    id: 1,
    firstName: "John",
    email: "john.doe@example.com",
    password: "123",
    taskCounts: { active: 2, newTask: 2, completed: 2, failed: 0 },
    tasks: [
      {
        title: "Fix login bug",
        description: "Resolve issue reported by QA",
        date: "2025-06-24",
        category: "DevOps",
        active: true,
        newTask: true,
        completed: true,
        failed: false,
      },
      {
        title: "Implement dashboard",
        description: "Design UI as per Figma",
        date: "2025-06-14",
        category: "Design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Write unit tests",
        description: "Ensure code coverage above 90%",
        date: "2025-06-01",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    firstName: "Jane",
    email: "jane.smith@example.com",
    password: "123",
    taskCounts: { active: 1, newTask: 1, completed: 2, failed: 1 },
    tasks: [
      {
        title: "Optimize database",
        description: "Improve SQL query performance",
        date: "2025-06-16",
        category: "Development",
        active: false,
        newTask: true,
        completed: true,
        failed: false,
      },
      {
        title: "Deploy to staging",
        description: "Check deployment success",
        date: "2025-06-11",
        category: "DevOps",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Review pull requests",
        description: "Check PR feedback",
        date: "2025-06-09",
        category: "Review",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Update documentation",
        description: "Write usage guides",
        date: "2025-06-04",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstName: "Michael",
    email: "michael.brown@example.com",
    password: "123",
    taskCounts: { active: 1, newTask: 2, completed: 2, failed: 0 },
    tasks: [
      {
        title: "Design landing page",
        description: "Design UI as per Figma",
        date: "2025-06-07",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Conduct user testing",
        description: "Run usability tests",
        date: "2025-06-10",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Set up CI/CD",
        description: "Connect GitHub actions",
        date: "2025-06-18",
        category: "DevOps",
        active: false,
        newTask: true,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: "Emily",
    email: "emily.jones@example.com",
    password: "123",
    taskCounts: { active: 1, newTask: 2, completed: 1, failed: 1 },
    tasks: [
      {
        title: "Write unit tests",
        description: "Ensure code coverage above 90%",
        date: "2025-06-05",
        category: "Testing",
        active: false,
        newTask: true,
        completed: true,
        failed: false,
      },
      {
        title: "Refactor auth module",
        description: "Clean up unused code",
        date: "2025-06-19",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Integrate payment gateway",
        description: "Connect with Razorpay API",
        date: "2025-06-08",
        category: "Development",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 5,
    firstName: "David",
    email: "david.wilson@example.com",
    password: "123",
    taskCounts: { active: 1, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        title: "Deploy to staging",
        description: "Check deployment success",
        date: "2025-06-06",
        category: "DevOps",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Fix login bug",
        description: "Resolve issue reported by QA",
        date: "2025-06-02",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Design landing page",
        description: "Design UI as per Figma",
        date: "2025-06-20",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: true,
      },
    ],
  },
];

export const admins = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admins", JSON.stringify(admins));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admins = JSON.parse(localStorage.getItem("admins"));

  return { employees, admins };
};
